version: '3.8'

services:
  candidature-service:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - candidature_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://candidaturedb:3306/candidatureDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - hr-service-network

  candidature_db:
    container_name: candidaturedb
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: candidatureDB
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hr-service-network
    command: --init-file /docker-entrypoint-initdb.d/init.sql

  init-script:
    image: mysql
    depends_on:
      - candidature_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  hr-service-network:
    driver: bridge
